### ISSUE TITLE
Setup all Paths in Windows Yet Still Getting "The system cannot find the path specified."

### ISSUE THREAD

**Issue by Dracrius** [progmem/Switch-Fightstick#12]
I followed a few guides linked in a fork that admitted all its code was from here and have confirmed I have GnuWin32, AVR 8bit Toolchain and LUFA all installed and referenced properly yet I get 3 `The system cannot find the path specified.` messages then it begins to compile and fails. I have one by one moved/deleted the windows path references to verify it is locating all 3 dependencies and it will fail with much more obvious error messages as soon as I did so. So as far as I can tell all 3 are being found by the installer so I am quite confused and can not find another place its looking for more paths.

Here is the entire error message 
```
D:\Switch-Frame-Advancer\Switch-Frame-Advancer>make
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
' [INFO]    :' Begin compilation of project \"Joystick\"...
""
avr-gcc (AVR_8_bit_GNU_Toolchain_3.6.2_1759) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

' [GCC]     :' Compiling C file \"Joystick.c\"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega32u4 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DF_CPU=16000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/  -I. -I./LUFA/LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_NONE -DF_USB=16000000UL  -MMD -MP -MF obj/Joystick.d Joystick.c -o obj/Joystick.o
Assembler messages:
Fatal error: can't create obj/Joystick.o: No such file or directory
Joystick.c:296:1: fatal error: error writing to -: Invalid argument
 }
 ^
compilation terminated.
make: *** [obj/Joystick.o] Error 1

```
I tried with 2 other forks but I was sure to download the master from here before reporting as I was hoping you had fixed something others had not!

**Comment by progmem** [comment]
If you can, run a `make clean` first, then run `make -n` and paste the output here. This will give us some more information, specifically what commands the system is saying it "cannot find the path specified" for.

One thing concerning is the format of the lines being printed: those are `echo` lines, and on Linux/macOS they would print like so:

```
 [INFO]    : Begin compilation of project "Joystick"...
(empty line, on purpose)
```

**Comment by progmem** [comment]
Since I haven't heard any response within the last couple of weeks, I'm assuming that you were able to resolve the issue on your end. I'm going to go ahead and close this; please let me know if this is still a problem!
