### ISSUE TITLE
I get Compiling issue

### ISSUE THREAD

**Issue by Dalk2ness** [progmem/Switch-Fightstick#14]
Today i install follow your step and stuck in some code
I have installed 

WinAVR-20100110
avr-gcc (WinAVR 20100110) 4.3.3
Copyright (C) 2008 Free Software Foundation, Inc.

My OS is Windows 10 64 bit
don't know....Why i get this error?

 [GCC]     : Compiling C file "Joystick.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega16u2 -fshort-enums -fno-inline-small-functions -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DF_CPU=16000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/   -I. -I./lufa/LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_NONE -DF_USB=16000000UL   -MMD -MP -MF obj/Joystick.d Joystick.c -o obj/Joystick.o
Assembler messages:
Fatal error: can't create obj/Joystick.o: No such file or directory
Joystick.c: In function 'SetupHardware':
Joystick.c:120: warning: implicit declaration of function 'clock_prescale_set'
Joystick.c:120: error: 'clock_div_1' undeclared (first use in this function)
Joystick.c:120: error: (Each undeclared identifier is reported only once
Joystick.c:120: error: for each function it appears in.)

**Comment by progmem** [comment]
Based on what I'm reading from [this thread](https://www.avrfreaks.net/forum/error-compiling-lufa-130901-windows-7-solved) WinAVR (being a decade old at this point) may not have every device properly declared within it (in the case of the 16u2).

Potential solutions to this would be as follows:
* The version of `avr-libc` in WinAVR can be patched to include the `clock_div_1` function
* The code for `clock_div_1` can be implemented separately
* Division can be turned off at the fuse level and the offending line commented out (requires an ISP programmer)
* A toolchain other than WinAVR can be used to build it, for example a Linux VM, WSL, or Microchip's own toolchain.

As a note, this code does build using the latest version of `avr-gcc` in both MacOS and Linux (Debian tested), so the last solution is a known working solution.
