### ISSUE TITLE
What about vibration feature?

### ISSUE THREAD

**Issue by glutesha** [progmem/Switch-Fightstick#17]

**Comment by progmem** [comment]
Vibration is outside of the scope of this project, for a few reasons:

* The Pokken controller, which was the reference for the descriptors used, does not have a rumble motor.
* The USB descriptors provided by this controller provides an output block (host sends data to controller for output), but in reviewing the data coming in this appears to be a mirror of the buttons that were pressed.
* My original interest, and the reason this project exists, was specifically in getting a fightstick built for the Switch. Adding rumble, a feature not available on most fightsticks, would have required a fair bit more in terms of resources available.

This project doesn't intend to be an all-encompassing solution, but rather a concept that a user could build on. If someone has access to a wired controller with rumble there isn't anything preventing that user from implementing those descriptors as well as the necessary changes to the `struct`s used to facilitate reads and writes, assuming that the controller isn't significantly more complicated than the Pokken controller is at a descriptor level.
