### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Xaruko** [progmem/Switch-Fightstick#18]
The title says it all, I tried setting my image for the splatoon printer but it comes up with this

C:\Users\user\Desktop\Switch-Fightstick-master>python bin2c.py test.data image.c
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Switch-Fightstick-master\bin2c.py", line 51, in <module>
    main(sys.argv[1:])
  File "C:\Users\user\Desktop\Switch-Fightstick-master\bin2c.py", line 19, in main
    for i in range(0, (320*120) / 8):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by progmem** [comment]
As a heads-up, this version of the codebase isn't related to the forks that others have made for e.g. the Splatoon meme printer. `bin2c.py` isn't a part of this codebase, and that error is specifically a Python error.
