### ISSUE TITLE
I cant create the .hex file.

### ISSUE THREAD

**Issue by spikehidden** [progmem/Switch-Fightstick#4]
I dont know what's wrong but somehow it didn't work.
If you need more information just ask me.
```
D:\download\Switch-Fightstick-master\Switch-Fightstick-master>make
      0 [main] sh 7604 sync_with_child: child 5356(0xB0) died before initializat
ion with status code 0xC0000142
    373 [main] sh 7604 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 3076 sync_with_child: child 9096(0x178) died before initializa
tion with status code 0xC0000142
    336 [main] sh 3076 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 7176 sync_with_child: child 8420(0x178) died before initializa
tion with status code 0xC0000142
    392 [main] sh 7176 sync_with_child: *** child state waitin
g for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
 [INFO]    : Begin compilation of project "Joystick"...

avr-gcc (WinAVR 20100110) 4.3.3
Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

../LUFA/LUFA/Build/DMBS/DMBS/gcc.mk:199: *** Source file does not exist: Joystic
k.c.  Stop.

D:\download\Switch-Fightstick-master\Switch-Fightstick-master>
```

**Comment by progmem** [comment]
Taking a look at the error, this is unrelated to this project specifically, but I'll do my best to offer assistance. I see one line that jumps out among the rest of these:

```
/usr/bin/sh: fork: Resource temporarily unavailable
```

Seeing this in a Windows environment makes me believe that either this is a machine with Linux Subsystem for Windows or a machine that has some *nix-like system like Cygwin on it. My assumption is based off of of this article [here](http://smallshire.org.uk/sufficientlysmall/2013/10/31/arduino-avr-gcc-eclipse-and-windows-8-1/), which mentions needing a different version of make installed and some PATH adjustments.

Taking a guess, avr-gcc's copy of make isn't being hit here, but a different version of make, and that's most likely causing some complications.
